# --- Configuración de Build CORREGIDA para Netlify ---
[build]
  # Base: El directorio donde vive tu proyecto de front-end.
  base = "client"
  
  # Command: ¡LA LÍNEA CLAVE! Primero instala dependencias, LUEGO construye.
  command = "npm install && npm run build"
  
  # Publish: El directorio que se debe publicar (relativo a 'base').
  publish = "dist"

# --- Reglas de Redirección (siguen igual y son correctas) ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
