# --- Configuración de Build DEFINITIVA para Netlify ---
[build]
  base = "client"
  
  # Command: Le decimos a Netlify que ejecute SOLAMENTE el build del front-end.
  command = "npm install && vite build"
  
  publish = "dist"

# --- Reglas de Redirección ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
